# Generated by Django 2.0.6 on 2019-12-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=True, help_text='决定着用户是否可登录管理后台', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='bigcourse',
            name='study_num',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='course',
            name='study_num',
            field=models.PositiveIntegerField(default=70),
        ),
    ]
